version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: Shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: viewsonic1986@@
    ports:
      - "5432:5432"