version: '3.8'

services:
  postgres:
    image: postgres
    depends_on:
      - postgres
    env_file:
      Shop.env
    environment:
      POSTGRES_DB: Shop
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"