spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_LOGIN}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

      matching-strategy: ant_path_matcher
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
springdoc:
  api-docs:
    enabled: true
